services:
  video-site-61:
    image: ghcr.io/iwwater/61video:stable
    container_name: video-site-61
    ports:
      - "6191:6191"
    volumes:
      - ./data:/opt/video-site-61/data
    restart: unless-stopped
